version: "3.8"

services:
  backend:
    build: .
    container_name: addressbook-backend
    ports:
      - "8080"
    environment:
      PORT: 8080
      MONGO_URI: "${MONGO_URI}"
    restart: always
